//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArthiPOS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArthiPOS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arthi App.
        /// </summary>
        internal static string a0000 {
            get {
                return ResourceManager.GetString("a0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string a0001 {
            get {
                return ResourceManager.GetString("a0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Product.
        /// </summary>
        internal static string a0002 {
            get {
                return ResourceManager.GetString("a0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string a0004 {
            get {
                return ResourceManager.GetString("a0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string a0005 {
            get {
                return ResourceManager.GetString("a0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string a0006 {
            get {
                return ResourceManager.GetString("a0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Paid Date.
        /// </summary>
        internal static string a0007 {
            get {
                return ResourceManager.GetString("a0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string a0008 {
            get {
                return ResourceManager.GetString("a0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string a0009 {
            get {
                return ResourceManager.GetString("a0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string a0011 {
            get {
                return ResourceManager.GetString("a0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string a0012 {
            get {
                return ResourceManager.GetString("a0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khata #.
        /// </summary>
        internal static string a0013 {
            get {
                return ResourceManager.GetString("a0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string a0014 {
            get {
                return ResourceManager.GetString("a0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Name.
        /// </summary>
        internal static string a0021 {
            get {
                return ResourceManager.GetString("a0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string a0022 {
            get {
                return ResourceManager.GetString("a0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Name.
        /// </summary>
        internal static string a0023 {
            get {
                return ResourceManager.GetString("a0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Received.
        /// </summary>
        internal static string a0030 {
            get {
                return ResourceManager.GetString("a0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing.
        /// </summary>
        internal static string a0031 {
            get {
                return ResourceManager.GetString("a0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string a0032 {
            get {
                return ResourceManager.GetString("a0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Amount.
        /// </summary>
        internal static string a0033 {
            get {
                return ResourceManager.GetString("a0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Account.
        /// </summary>
        internal static string a0034 {
            get {
                return ResourceManager.GetString("a0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Receive.
        /// </summary>
        internal static string a0035 {
            get {
                return ResourceManager.GetString("a0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Bill Amount.
        /// </summary>
        internal static string a0036 {
            get {
                return ResourceManager.GetString("a0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Amount.
        /// </summary>
        internal static string a0037 {
            get {
                return ResourceManager.GetString("a0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Amount.
        /// </summary>
        internal static string a0038 {
            get {
                return ResourceManager.GetString("a0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string a0039 {
            get {
                return ResourceManager.GetString("a0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string a0101 {
            get {
                return ResourceManager.GetString("a0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string a0102 {
            get {
                return ResourceManager.GetString("a0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string a0103 {
            get {
                return ResourceManager.GetString("a0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string a0104 {
            get {
                return ResourceManager.GetString("a0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipari.
        /// </summary>
        internal static string a0201 {
            get {
                return ResourceManager.GetString("a0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string a0202 {
            get {
                return ResourceManager.GetString("a0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string a0203 {
            get {
                return ResourceManager.GetString("a0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipari Name.
        /// </summary>
        internal static string a0204 {
            get {
                return ResourceManager.GetString("a0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string a0205 {
            get {
                return ResourceManager.GetString("a0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string a0206 {
            get {
                return ResourceManager.GetString("a0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord.
        /// </summary>
        internal static string a0207 {
            get {
                return ResourceManager.GetString("a0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipari Setting.
        /// </summary>
        internal static string a0208 {
            get {
                return ResourceManager.GetString("a0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Setting.
        /// </summary>
        internal static string a0209 {
            get {
                return ResourceManager.GetString("a0209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamidar.
        /// </summary>
        internal static string a0210 {
            get {
                return ResourceManager.GetString("a0210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chongi.
        /// </summary>
        internal static string a0301 {
            get {
                return ResourceManager.GetString("a0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string a0302 {
            get {
                return ResourceManager.GetString("a0302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour.
        /// </summary>
        internal static string a0303 {
            get {
                return ResourceManager.GetString("a0303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fright.
        /// </summary>
        internal static string a0304 {
            get {
                return ResourceManager.GetString("a0304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string a0305 {
            get {
                return ResourceManager.GetString("a0305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string a0306 {
            get {
                return ResourceManager.GetString("a0306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munchiana.
        /// </summary>
        internal static string a0307 {
            get {
                return ResourceManager.GetString("a0307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clerk.
        /// </summary>
        internal static string a0308 {
            get {
                return ResourceManager.GetString("a0308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazdori.
        /// </summary>
        internal static string a0309 {
            get {
                return ResourceManager.GetString("a0309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repayment.
        /// </summary>
        internal static string a0311 {
            get {
                return ResourceManager.GetString("a0311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string a0401 {
            get {
                return ResourceManager.GetString("a0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string a0402 {
            get {
                return ResourceManager.GetString("a0402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string a0403 {
            get {
                return ResourceManager.GetString("a0403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string a0404 {
            get {
                return ResourceManager.GetString("a0404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        internal static string a0405 {
            get {
                return ResourceManager.GetString("a0405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string a0406 {
            get {
                return ResourceManager.GetString("a0406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Quantity.
        /// </summary>
        internal static string a0407 {
            get {
                return ResourceManager.GetString("a0407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rent.
        /// </summary>
        internal static string a0501 {
            get {
                return ResourceManager.GetString("a0501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Labour.
        /// </summary>
        internal static string a0502 {
            get {
                return ResourceManager.GetString("a0502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string a0503 {
            get {
                return ResourceManager.GetString("a0503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sale.
        /// </summary>
        internal static string a0504 {
            get {
                return ResourceManager.GetString("a0504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount.
        /// </summary>
        internal static string a0505 {
            get {
                return ResourceManager.GetString("a0505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Labour.
        /// </summary>
        internal static string a0506 {
            get {
                return ResourceManager.GetString("a0506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Quantity.
        /// </summary>
        internal static string a0507 {
            get {
                return ResourceManager.GetString("a0507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rent.
        /// </summary>
        internal static string a0508 {
            get {
                return ResourceManager.GetString("a0508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Munshiana.
        /// </summary>
        internal static string a0509 {
            get {
                return ResourceManager.GetString("a0509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expense.
        /// </summary>
        internal static string a0510 {
            get {
                return ResourceManager.GetString("a0510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Chalan .
        /// </summary>
        internal static string a0511 {
            get {
                return ResourceManager.GetString("a0511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string a0512 {
            get {
                return ResourceManager.GetString("a0512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string a0601 {
            get {
                return ResourceManager.GetString("a0601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string a0602 {
            get {
                return ResourceManager.GetString("a0602", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string a0603 {
            get {
                return ResourceManager.GetString("a0603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string a0604 {
            get {
                return ResourceManager.GetString("a0604", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        internal static string a0605 {
            get {
                return ResourceManager.GetString("a0605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bill.
        /// </summary>
        internal static string a0606 {
            get {
                return ResourceManager.GetString("a0606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of sales.
        /// </summary>
        internal static string a1001 {
            get {
                return ResourceManager.GetString("a1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string a1002 {
            get {
                return ResourceManager.GetString("a1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string a1003 {
            get {
                return ResourceManager.GetString("a1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augrai.
        /// </summary>
        internal static string a1004 {
            get {
                return ResourceManager.GetString("a1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash InOut.
        /// </summary>
        internal static string a1005 {
            get {
                return ResourceManager.GetString("a1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string a1006 {
            get {
                return ResourceManager.GetString("a1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportings.
        /// </summary>
        internal static string a1007 {
            get {
                return ResourceManager.GetString("a1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string a1008 {
            get {
                return ResourceManager.GetString("a1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        internal static string a1009 {
            get {
                return ResourceManager.GetString("a1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string a1010 {
            get {
                return ResourceManager.GetString("a1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string a1011 {
            get {
                return ResourceManager.GetString("a1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want change language?.
        /// </summary>
        internal static string a1012 {
            get {
                return ResourceManager.GetString("a1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle #.
        /// </summary>
        internal static string a1013 {
            get {
                return ResourceManager.GetString("a1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string a1014 {
            get {
                return ResourceManager.GetString("a1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string a1015 {
            get {
                return ResourceManager.GetString("a1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoicing.
        /// </summary>
        internal static string a1016 {
            get {
                return ResourceManager.GetString("a1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bipari.
        /// </summary>
        internal static string a1017 {
            get {
                return ResourceManager.GetString("a1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Product.
        /// </summary>
        internal static string a1018 {
            get {
                return ResourceManager.GetString("a1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Product.
        /// </summary>
        internal static string a1019 {
            get {
                return ResourceManager.GetString("a1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Bills.
        /// </summary>
        internal static string a1020 {
            get {
                return ResourceManager.GetString("a1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Receving.
        /// </summary>
        internal static string a1021 {
            get {
                return ResourceManager.GetString("a1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expense.
        /// </summary>
        internal static string a1022 {
            get {
                return ResourceManager.GetString("a1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Bipari Sale.
        /// </summary>
        internal static string a1023 {
            get {
                return ResourceManager.GetString("a1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill.
        /// </summary>
        internal static string a1024 {
            get {
                return ResourceManager.GetString("a1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string a1025 {
            get {
                return ResourceManager.GetString("a1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission +Chongi.
        /// </summary>
        internal static string a1026 {
            get {
                return ResourceManager.GetString("a1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Details.
        /// </summary>
        internal static string a1027 {
            get {
                return ResourceManager.GetString("a1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search
        ///Name ,Khata# ,Bill id.
        /// </summary>
        internal static string a1028 {
            get {
                return ResourceManager.GetString("a1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Out/Expense.
        /// </summary>
        internal static string a1029 {
            get {
                return ResourceManager.GetString("a1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle #.
        /// </summary>
        internal static string a1030 {
            get {
                return ResourceManager.GetString("a1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        internal static string a1031 {
            get {
                return ResourceManager.GetString("a1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Commission.
        /// </summary>
        internal static string a1032 {
            get {
                return ResourceManager.GetString("a1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Chongi.
        /// </summary>
        internal static string a1033 {
            get {
                return ResourceManager.GetString("a1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipari Commission.
        /// </summary>
        internal static string a1034 {
            get {
                return ResourceManager.GetString("a1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipari Chongi.
        /// </summary>
        internal static string a1035 {
            get {
                return ResourceManager.GetString("a1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string a1036 {
            get {
                return ResourceManager.GetString("a1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string a1037 {
            get {
                return ResourceManager.GetString("a1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string a1038 {
            get {
                return ResourceManager.GetString("a1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Chalan.
        /// </summary>
        internal static string a1039 {
            get {
                return ResourceManager.GetString("a1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bill.
        /// </summary>
        internal static string a1040 {
            get {
                return ResourceManager.GetString("a1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Amount.
        /// </summary>
        internal static string a1041 {
            get {
                return ResourceManager.GetString("a1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string a1042 {
            get {
                return ResourceManager.GetString("a1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng Name.
        /// </summary>
        internal static string a1043 {
            get {
                return ResourceManager.GetString("a1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu Name.
        /// </summary>
        internal static string a1044 {
            get {
                return ResourceManager.GetString("a1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string a1045 {
            get {
                return ResourceManager.GetString("a1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old/Previous Amount.
        /// </summary>
        internal static string a1046 {
            get {
                return ResourceManager.GetString("a1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        internal static string a1047 {
            get {
                return ResourceManager.GetString("a1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ID/Name.
        /// </summary>
        internal static string a1048 {
            get {
                return ResourceManager.GetString("a1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string a1049 {
            get {
                return ResourceManager.GetString("a1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string a1050 {
            get {
                return ResourceManager.GetString("a1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Landloard/Customer.
        /// </summary>
        internal static string a1051 {
            get {
                return ResourceManager.GetString("a1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string a1052 {
            get {
                return ResourceManager.GetString("a1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string a1053 {
            get {
                return ResourceManager.GetString("a1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Season Report.
        /// </summary>
        internal static string a1054 {
            get {
                return ResourceManager.GetString("a1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        internal static string a1055 {
            get {
                return ResourceManager.GetString("a1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augrai Report.
        /// </summary>
        internal static string a1056 {
            get {
                return ResourceManager.GetString("a1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Recovery.
        /// </summary>
        internal static string a1057 {
            get {
                return ResourceManager.GetString("a1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit/Loss.
        /// </summary>
        internal static string a1058 {
            get {
                return ResourceManager.GetString("a1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Expenses.
        /// </summary>
        internal static string a1059 {
            get {
                return ResourceManager.GetString("a1059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Received.
        /// </summary>
        internal static string a1060 {
            get {
                return ResourceManager.GetString("a1060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission/Chongi.
        /// </summary>
        internal static string a1061 {
            get {
                return ResourceManager.GetString("a1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string a1062 {
            get {
                return ResourceManager.GetString("a1062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        internal static string a1063 {
            get {
                return ResourceManager.GetString("a1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investments.
        /// </summary>
        internal static string a1064 {
            get {
                return ResourceManager.GetString("a1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string a1065 {
            get {
                return ResourceManager.GetString("a1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string a1066 {
            get {
                return ResourceManager.GetString("a1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string a1067 {
            get {
                return ResourceManager.GetString("a1067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Date.
        /// </summary>
        internal static string a1068 {
            get {
                return ResourceManager.GetString("a1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Date.
        /// </summary>
        internal static string a1069 {
            get {
                return ResourceManager.GetString("a1069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        internal static string a1070 {
            get {
                return ResourceManager.GetString("a1070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Balance.
        /// </summary>
        internal static string a1071 {
            get {
                return ResourceManager.GetString("a1071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Balance.
        /// </summary>
        internal static string a1072 {
            get {
                return ResourceManager.GetString("a1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string a1073 {
            get {
                return ResourceManager.GetString("a1073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string a1074 {
            get {
                return ResourceManager.GetString("a1074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string a1075 {
            get {
                return ResourceManager.GetString("a1075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Balance.
        /// </summary>
        internal static string a1076 {
            get {
                return ResourceManager.GetString("a1076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string a1077 {
            get {
                return ResourceManager.GetString("a1077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string a1078 {
            get {
                return ResourceManager.GetString("a1078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string a1079 {
            get {
                return ResourceManager.GetString("a1079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string a1080 {
            get {
                return ResourceManager.GetString("a1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Sale.
        /// </summary>
        internal static string a1081 {
            get {
                return ResourceManager.GetString("a1081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Set Backup Path..
        /// </summary>
        internal static string a1082 {
            get {
                return ResourceManager.GetString("a1082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database  Restore Successefully.
        /// </summary>
        internal static string a1083 {
            get {
                return ResourceManager.GetString("a1083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backup Done Successefully.
        /// </summary>
        internal static string a1084 {
            get {
                return ResourceManager.GetString("a1084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Daily Sales.
        /// </summary>
        internal static string a1085 {
            get {
                return ResourceManager.GetString("a1085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string a1086 {
            get {
                return ResourceManager.GetString("a1086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string a1087 {
            get {
                return ResourceManager.GetString("a1087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERP (Sales, Expense ,Recovery &amp; Profit).
        /// </summary>
        internal static string a1088 {
            get {
                return ResourceManager.GetString("a1088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalan.
        /// </summary>
        internal static string a1089 {
            get {
                return ResourceManager.GetString("a1089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extra bill amount.
        /// </summary>
        internal static string a1090 {
            get {
                return ResourceManager.GetString("a1090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extra.
        /// </summary>
        internal static string a1091 {
            get {
                return ResourceManager.GetString("a1091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Click &apos;Yes&apos; to Delete the record..
        /// </summary>
        internal static string a1092 {
            get {
                return ResourceManager.GetString("a1092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string a1093 {
            get {
                return ResourceManager.GetString("a1093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string a1094 {
            get {
                return ResourceManager.GetString("a1094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Naqdi.
        /// </summary>
        internal static string a1095 {
            get {
                return ResourceManager.GetString("a1095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        internal static string a1096 {
            get {
                return ResourceManager.GetString("a1096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add Cash in Account....
        /// </summary>
        internal static string a1097 {
            get {
                return ResourceManager.GetString("a1097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Bipari.
        /// </summary>
        internal static string a1098 {
            get {
                return ResourceManager.GetString("a1098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Landlord.
        /// </summary>
        internal static string a1099 {
            get {
                return ResourceManager.GetString("a1099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense/Receivings.
        /// </summary>
        internal static string a1200 {
            get {
                return ResourceManager.GetString("a1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Product.
        /// </summary>
        internal static string a2000 {
            get {
                return ResourceManager.GetString("a2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string a2001 {
            get {
                return ResourceManager.GetString("a2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string a2002 {
            get {
                return ResourceManager.GetString("a2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string a2003 {
            get {
                return ResourceManager.GetString("a2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Cash.
        /// </summary>
        internal static string a2004 {
            get {
                return ResourceManager.GetString("a2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string a2005 {
            get {
                return ResourceManager.GetString("a2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string a2006 {
            get {
                return ResourceManager.GetString("a2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receving Date.
        /// </summary>
        internal static string a2007 {
            get {
                return ResourceManager.GetString("a2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment/Expense Date.
        /// </summary>
        internal static string a2008 {
            get {
                return ResourceManager.GetString("a2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string a2009 {
            get {
                return ResourceManager.GetString("a2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment/Expense.
        /// </summary>
        internal static string a2010 {
            get {
                return ResourceManager.GetString("a2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Expense.
        /// </summary>
        internal static string a2011 {
            get {
                return ResourceManager.GetString("a2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Augrai.
        /// </summary>
        internal static string a2012 {
            get {
                return ResourceManager.GetString("a2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        internal static string a2013 {
            get {
                return ResourceManager.GetString("a2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string a2014 {
            get {
                return ResourceManager.GetString("a2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Amount Customer.
        /// </summary>
        internal static string a2015 {
            get {
                return ResourceManager.GetString("a2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Amount Landlord.
        /// </summary>
        internal static string a2016 {
            get {
                return ResourceManager.GetString("a2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RQuantity.
        /// </summary>
        internal static string a2017 {
            get {
                return ResourceManager.GetString("a2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Khata and Receivings.
        /// </summary>
        internal static string a2018 {
            get {
                return ResourceManager.GetString("a2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augrai Difference.
        /// </summary>
        internal static string a2019 {
            get {
                return ResourceManager.GetString("a2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved..
        /// </summary>
        internal static string a2020 {
            get {
                return ResourceManager.GetString("a2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Amount.
        /// </summary>
        internal static string a2021 {
            get {
                return ResourceManager.GetString("a2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Amount.
        /// </summary>
        internal static string a2022 {
            get {
                return ResourceManager.GetString("a2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Bill.
        /// </summary>
        internal static string a2023 {
            get {
                return ResourceManager.GetString("a2023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sale.
        /// </summary>
        internal static string a2024 {
            get {
                return ResourceManager.GetString("a2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added in Database..
        /// </summary>
        internal static string added_in_database {
            get {
                return ResourceManager.GetString("added_in_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg2 {
            get {
                object obj = ResourceManager.GetObject("bg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipari Chongi.
        /// </summary>
        internal static string bipari_chongi {
            get {
                return ResourceManager.GetString("bipari_chongi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bipari Commission.
        /// </summary>
        internal static string bipari_commssion {
            get {
                return ResourceManager.GetString("bipari_commssion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeb {
            get {
                object obj = ResourceManager.GetObject("closeb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closewhite {
            get {
                object obj = ResourceManager.GetObject("closewhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Chongi.
        /// </summary>
        internal static string cust_chongi {
            get {
                return ResourceManager.GetString("cust_chongi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Commission.
        /// </summary>
        internal static string cust_commission {
            get {
                return ResourceManager.GetString("cust_commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del {
            get {
                object obj = ResourceManager.GetObject("del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del1 {
            get {
                object obj = ResourceManager.GetObject("del1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del2 {
            get {
                object obj = ResourceManager.GetObject("del2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del3 {
            get {
                object obj = ResourceManager.GetObject("del3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteitem {
            get {
                object obj = ResourceManager.GetObject("deleteitem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollar4 {
            get {
                object obj = ResourceManager.GetObject("dollar4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollor {
            get {
                object obj = ResourceManager.GetObject("dollor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollor1 {
            get {
                object obj = ResourceManager.GetObject("dollor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollor2 {
            get {
                object obj = ResourceManager.GetObject("dollor2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dollor3 {
            get {
                object obj = ResourceManager.GetObject("dollor3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap driver {
            get {
                object obj = ResourceManager.GetObject("driver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help1 {
            get {
                object obj = ResourceManager.GetObject("help1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Your Today Products..
        /// </summary>
        internal static string insert_product {
            get {
                return ResourceManager.GetString("insert_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection Problem..
        /// </summary>
        internal static string insertion_error {
            get {
                return ResourceManager.GetString("insertion_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyboard {
            get {
                object obj = ResourceManager.GetObject("keyboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord.
        /// </summary>
        internal static string landlord {
            get {
                return ResourceManager.GetString("landlord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string lbl_advance {
            get {
                return ResourceManager.GetString("lbl_advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string lbl_bipari_name {
            get {
                return ResourceManager.GetString("lbl_bipari_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Setting.
        /// </summary>
        internal static string lbl_bipari_setting {
            get {
                return ResourceManager.GetString("lbl_bipari_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chongi.
        /// </summary>
        internal static string lbl_chongi {
            get {
                return ResourceManager.GetString("lbl_chongi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string lbl_commisison {
            get {
                return ResourceManager.GetString("lbl_commisison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Setting.
        /// </summary>
        internal static string lbl_customer_setting {
            get {
                return ResourceManager.GetString("lbl_customer_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string lbl_expense {
            get {
                return ResourceManager.GetString("lbl_expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour.
        /// </summary>
        internal static string lbl_labour {
            get {
                return ResourceManager.GetString("lbl_labour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landlord.
        /// </summary>
        internal static string lbl_landlord_name {
            get {
                return ResourceManager.GetString("lbl_landlord_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munshiana.
        /// </summary>
        internal static string lbl_munshiana {
            get {
                return ResourceManager.GetString("lbl_munshiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string lbl_product_name {
            get {
                return ResourceManager.GetString("lbl_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        internal static string lbl_product_packing {
            get {
                return ResourceManager.GetString("lbl_product_packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string lbl_product_weight {
            get {
                return ResourceManager.GetString("lbl_product_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lbl_quantity {
            get {
                return ResourceManager.GetString("lbl_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Product.
        /// </summary>
        internal static string lbl_remaining_prodcut {
            get {
                return ResourceManager.GetString("lbl_remaining_prodcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        internal static string lbl_rent {
            get {
                return ResourceManager.GetString("lbl_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Products.
        /// </summary>
        internal static string lbl_total_Begs {
            get {
                return ResourceManager.GetString("lbl_total_Begs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Labour.
        /// </summary>
        internal static string lbl_total_labour {
            get {
                return ResourceManager.GetString("lbl_total_labour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Munshiana.
        /// </summary>
        internal static string lbl_total_munhiana {
            get {
                return ResourceManager.GetString("lbl_total_munhiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rent.
        /// </summary>
        internal static string lbl_total_rent {
            get {
                return ResourceManager.GetString("lbl_total_rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Product.
        /// </summary>
        internal static string lbl_totalitems {
            get {
                return ResourceManager.GetString("lbl_totalitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle No.
        /// </summary>
        internal static string lbl_vehicle_no {
            get {
                return ResourceManager.GetString("lbl_vehicle_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lSquareRulerCm {
            get {
                object obj = ResourceManager.GetObject("lSquareRulerCm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Fee.
        /// </summary>
        internal static string marketfee {
            get {
                return ResourceManager.GetString("marketfee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu00 {
            get {
                object obj = ResourceManager.GetObject("menu00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu1 {
            get {
                object obj = ResourceManager.GetObject("menu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuwhite {
            get {
                object obj = ResourceManager.GetObject("menuwhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuxxx {
            get {
                object obj = ResourceManager.GetObject("menuxxx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inserted Successfully..
        /// </summary>
        internal static string msg_database_success {
            get {
                return ResourceManager.GetString("msg_database_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nest {
            get {
                object obj = ResourceManager.GetObject("nest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previou {
            get {
                object obj = ResourceManager.GetObject("previou", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pro {
            get {
                object obj = ResourceManager.GetObject("pro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profile {
            get {
                object obj = ResourceManager.GetObject("profile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profilex {
            get {
                object obj = ResourceManager.GetObject("profilex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap profilex1 {
            get {
                object obj = ResourceManager.GetObject("profilex1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Report.
        /// </summary>
        internal static string rd1 {
            get {
                return ResourceManager.GetString("rd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Report.
        /// </summary>
        internal static string rd2 {
            get {
                return ResourceManager.GetString("rd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BipariReport.
        /// </summary>
        internal static string rd3 {
            get {
                return ResourceManager.GetString("rd3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Report.
        /// </summary>
        internal static string rd4 {
            get {
                return ResourceManager.GetString("rd4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augrai Total Report.
        /// </summary>
        internal static string rd5 {
            get {
                return ResourceManager.GetString("rd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Deleted..
        /// </summary>
        internal static string record_delete {
            get {
                return ResourceManager.GetString("record_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh1x {
            get {
                object obj = ResourceManager.GetObject("refresh1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right1 {
            get {
                object obj = ResourceManager.GetObject("right1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap t_dollor {
            get {
                object obj = ResourceManager.GetObject("t_dollor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tile {
            get {
                object obj = ResourceManager.GetObject("tile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vewitem {
            get {
                object obj = ResourceManager.GetObject("vewitem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
